version: '3.8'

# https://www.keycloak.org/guides#server
# https://www.keycloak.org/getting-started/getting-started-docker
# Angular: https://github.com/mauriciovigolo/keycloak-angular

services:
  postgres:
    image: postgres:16
    container_name: dc-keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: dc-keycloak-server
    restart: unless-stopped
    command: start-dev
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      
      # Configuration admin
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      
      # Configuration du serveur
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      
      # Désactiver HTTPS en développement
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_CERTIFICATE_FILE: ""
      KC_HTTPS_CERTIFICATE_KEY_FILE: ""
    ports:
      - ${KC_HOSTNAME_PORT}:8080
    depends_on:
      - postgres
    networks:
      - keycloak-network

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge
